#!/bin/bash
if [ -s $1 ];then
    name=$1
else
    if [ -s $1.grd ];then
	name=$1.grd
    else
	echo $1 or $1.grd are nonexistent.
	exit
    fi
fi
region=$2 

echo `grdinfo -C $name $region | gawk '{print($11)}'`
